### ISSUE TITLE
CSProj references files not present

### ISSUE THREAD

**Issue by chadcarlton** [microsoftgraph/aspnet-security-api-sample#1]
/FilterConfig.cs
/ApplicationInsights.config
/ErrorHandler/AiHandleErrorAttribute.cs
/Connected Services/Application Insights/ConnectedService.json

Are referenced in the csproj file, but are not in the repo.
(you may want to remove the contents of /Properties/PublishProfiles)

**Comment by Mounika-Chillamcherla** [comment]
Removed the unnecessary references
