### ISSUE TITLE
Unable to Sign-in

### ISSUE THREAD

**Issue by zacharymollenhour** [microsoftgraph/aspnet-security-api-sample#11]

**Comment by Mounika-Chillamcherla** [comment]
Can you try in a different browser or in incognito and see if the problem still exists?

**Comment by zacharymollenhour** [comment]
Only happened locally. When i deployed to azure the issue went away. Could be related to still not having admin rights granted by the tenant admin. Thanks

**Comment by Mounika-Chillamcherla** [comment]
Thanks for your response. We will try our best to not have these kind of issues in the future.
