### ISSUE TITLE
Dashboard empty

### ISSUE THREAD

**Issue by sailando** [microsoftgraph/aspnet-security-api-sample#35]
Deployed v3.0 to my Azure subscription.
Built with VSCE 2019.
When I open the application, logon is successfully completed, but the dashboard is empty, no data.
Even if I have just 1 alert in MCAS so far, shouldn't I at least see the list of Security Providers?

**Comment by mshalev** [comment]
Hi,
The list of security providers is dynamically created based on the alerts in the tenant - it does not list providers from which you are not receiving alerts.
What other Security Products do you have deployed to this Azure AD tenant?
If you have Azure Security Center deployed, you need to enable Data Collection Services for the alerts to be available for querying via the Graph Security API.
Are you seeing other alerts in the product portals that you are not seeing in the Demo application?
If so, please send us details including the tenantId, product, and if you can see the alertId - it as well.

Thanks,
Michael

**Comment by sailando** [comment]
ASC is fully functional, I see alerts from WDATP on servers lighting up in ASC Threat Protection blade.
Today I have alerts from ASC, WDATP and MCAS in my alert list. Lets see if the dashboard will update later.

cheers, Jörg
