### ISSUE TITLE
Alert update does not finish, alert cannot be opened afterwards

### ISSUE THREAD

**Issue by sailando** [microsoftgraph/aspnet-security-api-sample#36]
I deployed v3.0 to my Azure subscription.
Built with VSCE 2019.
I have just 1 alert from MCAS so far.
When I update the alert, the spinning dots never stop and the alert cannot be opened anymore (after leaving the page).

**Comment by mshalev** [comment]
Hi,

Please provide details to allow us to try and understand the cause for this behavior:
Azure AD tenantId, and alertId if you can see it.

THanks,
Michael

**Comment by sailando** [comment]
Sorry, have been off for while.
            "id": "da636953302188934593_1400162912",
            "azureTenantId": "670cf7bf-fd34-499e-8d24-7ff0f270d16d",
I could update this alert today (change to "resolved"). I had added application permissions for a while, not sure if that made the behavior change. Don't see the change in WD security center, though.

thanks for your support, Jörg
