### ISSUE TITLE
Unable to subscribe security alert notifications.

### ISSUE THREAD

**Issue by lokeshwarreddy** [microsoftgraph/aspnet-security-api-sample#5]
I clone the code and tried to execute on my system.  The first part of the UI where the alerts are listed is working fine for me, but while working with notifications I am receiving the following error....

`Unhandled Exception:
Microsoft.Graph.ServiceException: Code: ExtensionError
Message: Operation: Create; Exception: [Status Code: InternalServerError; Reason: Internal Server Error]

Inner error
Message: ISG Subscription Service does not work properly. Transformed subscription is invalid`

I am executing the web app with my azure work account and having difficulty to know the reason behind this error.  Do I need to enable/configure some service to make this work?  Other subscriptions (Users, Groups and mail) works fine for me and I am seeing the above error only for /security/alerts endpoint.  Please help.  Thanks.

**Comment by Mounika-Chillamcherla** [comment]
We do not allow to create subscriptions on /security/alerts, as it's two wide.
Users can create subscriptions in 2 ways:
1. By using a filter in the resource uri
      Ex: /security/alerts?$filter=vendorInformation/provider eq 'IPC'
2. By using an alertid
     Ex: /security/alerts/alert_id_value

**Comment by lokeshwarreddy** [comment]
Thanks Mounika.
