### ISSUE TITLE
Error in /Home/Subscribe: Location header not present in redirection response.

### ISSUE THREAD

**Issue by mennolaan** [microsoftgraph/aspnet-security-api-sample#9]
When trying to subscribe i get the error Error in /Home/Subscribe: Location header not present in redirection response. From the graphserviceclient in  public async Task<ActionResult> Subscribe(SubscriptionFilters subscriptionFilters). I did remove the line  // requestMessage.Headers.Add("SampleID", "aspnet-connect-sample"); from GraphServiceClient to see if it made a change, but unfortunately it didn't

**Comment by Mounika-Chillamcherla** [comment]
Can you pull the recent changes and try again?? Our recent push has a lot of changes
